### ISSUE TITLE
nice plugin :)

### ISSUE THREAD

**Issue by kibotu** [amatkivskiy/localise-gradle-plugin#4]
just wanted to share the way i handled it so far:

https://gist.github.com/kibotu/9c2f6b724e90f3536af33bcd12293765

have a nice day

**Comment by amatkivskiy** [comment]
@kibotu  Thanks 👍 
Previously I also used a similar script to download localisations for the app. Unfortunately for my case I needed translations for multiple languages which was really difficult to implement within initial solution. That's why I decided to have more declarative tool to deal with it.

**Comment by amatkivskiy** [comment]
@kibotu Will close it for now. You  can join gitter room and discuss this plugin.  
https://gitter.im/amatkivskiy/localise-gradle-plugin
